#!/bin/sh /etc/rc.common

START=95
STOP=10
USE_PROCD=1

start_service() {
	config_load mt76x8-powersave
	config_get_bool enabled main enabled 1
	config_get_bool auto_suspend main auto_suspend 0

	[ "$enabled" -eq 1 ] || return 0
	[ "$auto_suspend" -eq 1 ] || return 0

	procd_open_instance
	procd_set_param command /usr/sbin/mt76x8-powersave monitor
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger mt76x8-powersave
}
