name: Build Firmware (PR) on ht-hd01-v2

permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
    paths:
    - 'boards/ht-hd01-v2/**'
    - 'boards/common/**'
    - 'include/kernel*'
    - 'package/base-files/**'
    - 'package/network/services/edgez-subnet-routes/**'
    - 'package/kernel/**'
    - 'patches/ht-hd01-v2/**'
    - 'target/linux/ramips/**'
    - 'feeds.conf.default'
    - '.github/workflows/build-firmware.yml'
    - '.github/workflows/build-pr-hd01v2.yml'

jobs:
  build-hd01-v2:
    name: Build HD01 V2
    uses: ./.github/workflows/build-firmware.yml
    with:
      board: ht-hd01-v2
      target: ramips
      subtarget: mt76x8
      description: "Heltec HT-HD01 V2 (MT76x8)"
